name: Release

on:
  release:
    types: [created]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CGO_CFLAGS: "-O -D__BLST_PORTABLE__"
  CGO_CFLAGS_ALLOW: "-O -D__BLST_PORTABLE__"
  GIT_TAG: ${{ github.ref_name }}

jobs:
  build:
    name: Build Release
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    steps:
      - name: Checkout Code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install zstd (MacOS)
        if: matrix.os == 'macos-latest'
        run: brew install zstd

      # ==============================
      #       Linux Cross Compile for AMD64
      # ==============================

      - name: Download musl-cross Toolchain (AMD64)
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget -q https://github.com/cross-tools/musl-cross/releases/download/20250520/x86_64-unknown-linux-musl.tar.xz
          echo "a896bad67a4dae7cd7baece62d537fda07f8c74e65fee1b450a691b83e151a9c  x86_64-unknown-linux-musl.tar.xz" | sha256sum -c -
          tar -xJf ./x86_64-unknown-linux-musl.tar.xz

      - name: Build Binary for Linux AMD64
        if: matrix.os == 'ubuntu-latest'
        run: |
          go mod download
          GIT_COMMIT=$(git rev-parse HEAD)
          GIT_COMMIT_DATE=$(git log -n1 --pretty='format:%cd' --date=format:'%Y%m%d')
          echo $GIT_COMMIT $GIT_COMMIT_DATE
          GOOS=linux GOARCH=amd64 CGO_ENABLED=1 CC=$(pwd)/x86_64-unknown-linux-musl/bin/x86_64-unknown-linux-musl-gcc go build -ldflags "-X main.gitCommit=$GIT_COMMIT -X main.gitDate=$GIT_COMMIT_DATE -extldflags=-static" -o ./build/bin/vic-geth-linux-amd64 -a ./cmd/geth
          tar -cf - -C ./build/bin vic-geth-linux-amd64 | zstd -o ./build/bin/vic-geth-$GIT_TAG-linux-amd64.tar.zst

      # ==============================
      #       Linux Cross Compile for ARM64
      # ==============================

      - name: Download musl-cross Toolchain (ARM64)
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget -q https://github.com/cross-tools/musl-cross/releases/download/20250520/aarch64-unknown-linux-musl.tar.xz
          echo "76f0d71893f3864e91ad09feff71a719cdf94cccd4f14cc25d7deed395968b5b  aarch64-unknown-linux-musl.tar.xz" | sha256sum -c -
          tar -xJf ./aarch64-unknown-linux-musl.tar.xz

      - name: Build Binary for Linux ARM64
        if: matrix.os == 'ubuntu-latest'
        run: |
          go mod download
          GIT_COMMIT=$(git rev-parse HEAD)
          GIT_COMMIT_DATE=$(git log -n1 --pretty='format:%cd' --date=format:'%Y%m%d')
          echo $GIT_COMMIT $GIT_COMMIT_DATE
          GOOS=linux GOARCH=arm64 CGO_ENABLED=1 CC=$(pwd)/aarch64-unknown-linux-musl/bin/aarch64-unknown-linux-musl-gcc go build -ldflags "-X main.gitCommit=$GIT_COMMIT -X main.gitDate=$GIT_COMMIT_DATE -extldflags=-static" -o ./build/bin/vic-geth-linux-arm64 -a ./cmd/geth
          tar -cf - -C ./build/bin vic-geth-linux-arm64 | zstd -o ./build/bin/vic-geth-$GIT_TAG-linux-arm64.tar.zst

      # ==============================
      #       Windows
      # ==============================

      - name: Build Binary for Windows AMD64
        if: matrix.os == 'windows-latest'
        run: |
          go mod download
          $GIT_COMMIT=git rev-parse HEAD
          $GIT_COMMIT_DATE=$(git log -n1 --pretty='format:%cd' --date=format:'%Y%m%d')
          Write-Host $GIT_COMMIT $GIT_COMMIT_DATE
          go build -ldflags "-X main.gitCommit=$GIT_COMMIT -X main.gitDate=$GIT_COMMIT_DATE" -o ./build/bin/vic-geth-windows-amd64.exe -a ./cmd/geth
          Compress-Archive -Path ./build/bin/vic-geth-windows-amd64.exe -DestinationPath ./build/bin/vic-geth-$env:GIT_TAG-windows-amd64.zip

      # ==============================
      #       MacOS
      # ==============================

      - name: Build Binary for MacOS ARM64
        if: matrix.os == 'macos-latest'
        run: |
          go mod download
          GIT_COMMIT=$(git rev-parse HEAD)
          GIT_COMMIT_DATE=$(git log -n1 --pretty='format:%cd' --date=format:'%Y%m%d')
          echo $GIT_COMMIT $GIT_COMMIT_DATE
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=1 go build -ldflags "-X main.gitCommit=$GIT_COMMIT -X main.gitDate=$GIT_COMMIT_DATE" -o ./build/bin/vic-geth-macos-arm64 -a ./cmd/geth
          tar -cf - -C ./build/bin vic-geth-macos-arm64 | zstd -o ./build/bin/vic-geth-$GIT_TAG-macos-arm64.tar.zst

      # ==============================
      #       Upload artifacts
      # ==============================

      - name: Upload Linux Build
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: matrix.os == 'ubuntu-latest'
        with:
          name: linux-amd64
          path: ./build/bin/vic-geth-${{ env.GIT_TAG }}-linux-amd64.tar.zst

      - name: Upload ARM64 Build
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: matrix.os == 'ubuntu-latest'
        with:
          name: linux-arm64
          path: ./build/bin/vic-geth-${{ env.GIT_TAG }}-linux-arm64.tar.zst

      - name: Upload Windows Build
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: matrix.os == 'windows-latest'
        with:
          name: windows-amd64
          path: ./build/bin/vic-geth-${{ env.GIT_TAG }}-windows-amd64.zip

      - name: Upload MacOS Build
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: matrix.os == 'macos-latest'
        with:
          name: macos-arm64
          path: ./build/bin/vic-geth-${{ env.GIT_TAG }}-macos-arm64.tar.zst

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      # ==============================
      #       Download artifacts
      # ==============================

      - name: Download linux-amd64 artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: linux-amd64
          path: .

      - name: Download linux-arm64 artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: linux-arm64
          path: .

      - name: Download windows-amd64 artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: windows-amd64
          path: .

      - name: Download macos-arm64 artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: macos-arm64
          path: .

      # ==============================
      #       Create release
      # ==============================

      - name: Create Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            "Created by Github Actions"
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            ./vic-geth-${{ github.ref_name }}-linux-amd64.tar.zst
            ./vic-geth-${{ github.ref_name }}-linux-arm64.tar.zst
            ./vic-geth-${{ github.ref_name }}-windows-amd64.zip
            ./vic-geth-${{ github.ref_name }}-macos-arm64.tar.zst
